[build]
  command = "npm run build && cp -r .next/static .next/server/app/static"
  publish = ".next/server/app"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 