[build]
  command = "npm run build"
  publish = ".next/server/app"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    skip_plugin = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 