[build]
  command = "npm run build && mkdir -p out && cp -r .next/server/app/* out/ && cp -r .next/static out/"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 